// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest        = require("bs-jest/lib/js/src/jest.js");
var Game$Tetris = require("../src/tetris/game.js");

describe("game", (function () {
        var piece = /* array */[
          /* Empty */1,
          /* Block */0,
          /* Empty */1,
          /* Empty */1,
          /* Block */0,
          /* Empty */1,
          /* Block */0,
          /* Block */0,
          /* Empty */1
        ];
        Jest.test("#range", (function () {
                var range = Game$Tetris.range(0, 3);
                return Jest.Expect[/* toEqual */12](/* :: */[
                              0,
                              /* :: */[
                                1,
                                /* :: */[
                                  2,
                                  /* [] */0
                                ]
                              ]
                            ])(Jest.Expect[/* expect */0](range));
              }));
        Jest.test("#blockAt", (function () {
                var block = Game$Tetris.blockAt(2, 2, 1, 0, piece);
                return Jest.Expect[/* toEqual */12](/* Some */[/* Block */0])(Jest.Expect[/* expect */0](block));
              }));
        Jest.test("#rotateRight", (function () {
                var expected = /* array */[
                  /* Block */0,
                  /* Empty */1,
                  /* Empty */1,
                  /* Block */0,
                  /* Block */0,
                  /* Block */0,
                  /* Block */0,
                  /* Empty */1,
                  /* Empty */1
                ];
                var rotated = Game$Tetris.rotateRight(piece);
                return Jest.Expect[/* toBe */2](expected)(Jest.Expect[/* expect */0](rotated));
              }));
        Jest.test("#rotateLeft", (function () {
                var expected = /* int array */[
                  /* Block */0,
                  /* Block */0,
                  /* Empty */1,
                  /* Empty */1
                ];
                var rotated = Game$Tetris.rotateLeft(piece);
                return Jest.Expect[/* toBe */2](expected)(Jest.Expect[/* expect */0](rotated));
              }));
        return Jest.test("#isColliding", (function () {
                      return Jest.Expect[/* toBe */2](/* true */1)(Jest.Expect[/* expect */0](/* true */1));
                    }));
      }));

/*  Not a pure module */
