// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';


var tileSize = 16;

var boardSize = /* record */[
  /* height */50,
  /* width */20
];

exports.tileSize  = tileSize;
exports.boardSize = boardSize;
/* No side effect */
