// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


var tileSize = 16;

var pieceSize = 4;

var boardSize = /* record */[
  /* height */50,
  /* width */20
];

exports.tileSize  = tileSize;
exports.pieceSize = pieceSize;
exports.boardSize = boardSize;
/* No side effect */
