// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Header");

function make(text, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("h1", undefined, text);
    });
  return newrecord;
}

var Header = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("Section");

function make$1(children) {
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.createDomElement("section", { }, children);
    });
  return newrecord;
}

var Section = /* module */[
  /* component */component$1,
  /* make */make$1
];

exports.Header  = Header;
exports.Section = Section;
/* component Not a pure module */
