// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var Block            = require("bs-platform/lib/js/block.js");
var Curry            = require("bs-platform/lib/js/curry.js");
var React            = require("react");
var Random           = require("bs-platform/lib/js/random.js");
var Caml_int32       = require("bs-platform/lib/js/caml_int32.js");
var Pervasives       = require("bs-platform/lib/js/pervasives.js");
var ReasonReact      = require("reason-react/lib/js/src/reasonReact.js");
var Constants$Tetris = require("./constants.js");

var seed = (parseInt(Math.random() * Number.MAX_SAFE_INTEGER));

console.log(/* tuple */[
      "Seed",
      seed
    ]);

Random.init(seed);

var boardStyle = {
  border: "1px solid black",
  height: Pervasives.string_of_int(Caml_int32.imul(Constants$Tetris.boardSize[/* height */0], Constants$Tetris.tileSize)) + "px",
  margin: "auto",
  width: Pervasives.string_of_int(Caml_int32.imul(Constants$Tetris.boardSize[/* width */1], Constants$Tetris.tileSize)) + "px"
};

function newShape() {
  var rnd = Random.$$int(3);
  if (rnd > 2 || rnd < 0) {
    return /* Square */0;
  } else {
    return rnd;
  }
}

function handleTick(state) {
  var match = state[/* activePiece */2];
  if (match) {
    console.log(/* tuple */[
          "Active shape",
          match[0]
        ]);
    return /* Update */Block.__(0, [/* record */[
                /* tick */state[/* tick */0] + 1 | 0,
                /* board */state[/* board */1],
                /* activePiece */state[/* activePiece */2]
              ]]);
  } else {
    var shape = newShape(/* () */0);
    var activePiece = /* Some */[/* record */[
        /* shape */shape,
        /* state : None */0,
        /* offsetX */0,
        /* offsetY */0
      ]];
    console.log(/* tuple */[
          "Creating active shape",
          activePiece
        ]);
    return /* Update */Block.__(0, [/* record */[
                /* tick */state[/* tick */0] + 2 | 0,
                /* board */state[/* board */1],
                /* activePiece */activePiece
              ]]);
  }
}

function handleMove(_, state) {
  return /* Update */Block.__(0, [state]);
}

var component = ReasonReact.reducerComponent("GameBoard");

function make() {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (self) {
      setInterval(Curry._1(self[/* reduce */3], (function () {
                  return /* Tick */0;
                })), 1000);
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (param) {
      return React.createElement("div", {
                  style: boardStyle
                }, Pervasives.string_of_int(param[/* state */4][/* tick */0]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* tick */0,
              /* board : [] */0,
              /* activePiece : None */0
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (typeof action === "number") {
        if (action !== 0) {
          return /* Update */Block.__(0, [state]);
        } else {
          return handleTick(state);
        }
      } else {
        return /* Update */Block.__(0, [state]);
      }
    });
  return newrecord;
}

exports.seed       = seed;
exports.boardStyle = boardStyle;
exports.newShape   = newShape;
exports.handleTick = handleTick;
exports.handleMove = handleMove;
exports.component  = component;
exports.make       = make;
/* seed Not a pure module */
