// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe       = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact      = require("reason-react/lib/js/src/reasonReact.js");
var Elements$Tetris  = require("./elements.js");
var GameBoard$Tetris = require("./gameBoard.js");

var component = ReasonReact.statelessComponent("Container");

function make(header, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Elements$Tetris.Section[/* make */1](/* array */[
                      ReasonReact.element(/* None */0, /* None */0, Elements$Tetris.Header[/* make */1](header, /* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, GameBoard$Tetris.make(/* array */[]))
                    ]));
    });
  return newrecord;
}

var Container = /* module */[
  /* component */component,
  /* make */make
];

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, make("tetris", /* array */[])), "index");

exports.Container = Container;
/* component Not a pure module */
