// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

function shapeToGrid(shape) {
  switch (shape) {
    case 0 : 
        return /* :: */[
                /* Block */0,
                /* :: */[
                  /* Block */0,
                  /* :: */[
                    /* Empty */1,
                    /* :: */[
                      /* Empty */1,
                      /* :: */[
                        /* Block */0,
                        /* :: */[
                          /* Block */0,
                          /* :: */[
                            /* Empty */1,
                            /* :: */[
                              /* Empty */1,
                              /* :: */[
                                /* Empty */1,
                                /* :: */[
                                  /* Empty */1,
                                  /* :: */[
                                    /* Empty */1,
                                    /* :: */[
                                      /* Empty */1,
                                      /* :: */[
                                        /* Empty */1,
                                        /* :: */[
                                          /* Empty */1,
                                          /* :: */[
                                            /* Empty */1,
                                            /* :: */[
                                              /* Empty */1,
                                              /* [] */0
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ];
    case 1 : 
        return /* :: */[
                /* Block */0,
                /* :: */[
                  /* Block */0,
                  /* :: */[
                    /* Empty */1,
                    /* :: */[
                      /* Empty */1,
                      /* :: */[
                        /* Empty */1,
                        /* :: */[
                          /* Block */0,
                          /* :: */[
                            /* Block */0,
                            /* :: */[
                              /* Empty */1,
                              /* :: */[
                                /* Empty */1,
                                /* :: */[
                                  /* Empty */1,
                                  /* :: */[
                                    /* Empty */1,
                                    /* :: */[
                                      /* Empty */1,
                                      /* :: */[
                                        /* Empty */1,
                                        /* :: */[
                                          /* Empty */1,
                                          /* :: */[
                                            /* Empty */1,
                                            /* :: */[
                                              /* Empty */1,
                                              /* [] */0
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ];
    case 2 : 
        return /* :: */[
                /* Empty */1,
                /* :: */[
                  /* Empty */1,
                  /* :: */[
                    /* Block */0,
                    /* :: */[
                      /* Block */0,
                      /* :: */[
                        /* Empty */1,
                        /* :: */[
                          /* Block */0,
                          /* :: */[
                            /* Block */0,
                            /* :: */[
                              /* Empty */1,
                              /* :: */[
                                /* Empty */1,
                                /* :: */[
                                  /* Empty */1,
                                  /* :: */[
                                    /* Empty */1,
                                    /* :: */[
                                      /* Empty */1,
                                      /* :: */[
                                        /* Empty */1,
                                        /* :: */[
                                          /* Empty */1,
                                          /* :: */[
                                            /* Empty */1,
                                            /* :: */[
                                              /* Empty */1,
                                              /* [] */0
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ];
    case 3 : 
    case 4 : 
    case 5 : 
    case 6 : 
        return /* [] */0;
    
  }
}

var component = ReasonReact.statelessComponent("Tetromino");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, "test");
    });
  return newrecord;
}

exports.shapeToGrid = shapeToGrid;
exports.component   = component;
exports.make        = make;
/* component Not a pure module */
